import fs from "node:fs/promises";
import path from "node:path";

/**
 * IO HELPERS
 * High-quality file system operations.
 */

/**
 * Reads and parses a JSON file.
 */
export async function readJson<T>(file: string): Promise<T> {
  const txt = await fs.readFile(file, "utf-8");
  return JSON.parse(txt) as T;
}

/**
 * Writes a JSON file with standard formatting.
 */
export async function writeJson<T>(
  file: string,
  data: T,
  addGeneratedMarker = true,
): Promise<void> {
  let finalData: any = data;
  if (
    addGeneratedMarker &&
    typeof data === "object" &&
    data !== null &&
    !Array.isArray(data)
  ) {
    finalData = {
      _generated: "DO NOT EDIT - This file is automatically generated",
      ...(data as object),
    };
  }
  const json = JSON.stringify(finalData, null, 2).trim() + "\n";
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, json, "utf-8");
}

/**
 * Writes a Markdown file with a standard generated warning.
 */
export async function writeMarkdown(
  file: string,
  content: string,
): Promise<void> {
  const header = `<!--
DO NOT EDIT THIS FILE MANUALLY!
This file is automatically generated by a script.
Any manual changes will be overwritten during the next generation.
-->\n\n`;
  await writeText(file, header + content);
}

/**
 * Writes a text file, ensuring the directory exists and has a trailing newline.
 */
export async function writeText(file: string, content: string): Promise<void> {
  const trimmed = content.trim() + "\n";
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, trimmed, "utf-8");
}

/**
 * Checks if a file exists.
 */
export async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Safely creates a directory.
 */
export async function ensureDir(dirPath: string): Promise<void> {
  await fs.mkdir(dirPath, { recursive: true });
}
